### ISSUE TITLE
Feature: 닉네임을 검증하여 올바른 경우 시작하기 버튼을 활성화 하고, 올바르지 않은 경우 경고 문구를 표시한다.

### ISSUE THREAD

**Issue by Byeonjin** [boostcampwm2023/web13_Boarlog#12]
## Feature Description

여기에 작성하세요

## To-Do

- [ ] Todo1
- [ ] Todo2
- [ ] Todo3

### 추가 사항

여기에 작성하세요

**Comment by LellowMellow** [comment]
초기 로그인 시에 닉네임을 입력하는 로직이 제거되었기 때문에 close 합니다.
