### ISSUE TITLE
Feature: 활성화된 시작하기 버튼을 클릭하면 메인 페이지로 이동한다. (검증, 분기 처리)

### ISSUE THREAD

**Issue by Byeonjin** [boostcampwm2023/web13_Boarlog#13]
## Feature Description

여기에 작성하세요

## To-Do

- [ ] Todo1
- [ ] Todo2
- [ ] Todo3

### 추가 사항

여기에 작성하세요

**Comment by LellowMellow** [comment]
초기 로그인 시에 닉네임을 입력하는 로직이 제거되었기 때문에 close 합니다.
