### ISSUE TITLE
Feature: 닉네임이 중복되었으면 경고 모달을 표시한다. (모달 구현)

### ISSUE THREAD

**Issue by Byeonjin** [boostcampwm2023/web13_Boarlog#14]
## Feature Description

여기에 작성하세요

## To-Do

- [ ] Todo1
- [ ] Todo2
- [ ] Todo3

### 추가 사항

여기에 작성하세요

**Comment by LellowMellow** [comment]
초기 로그인 시에 닉네임을 입력하는 로직이 제거되었기 때문에 close 합니다.
