### ISSUE TITLE
Feature: eslint와 prettier 설정을 완료한다.

### ISSUE THREAD

**Issue by Byeonjin** [boostcampwm2023/web13_Boarlog#4]
## Feature Description

협업을 위해 코드 컨벤션을 설정했습니다.

## To-Do

- [X] eslint 적용
- [X] prettier 적용

**Comment by platinouss** [comment]
[Boarlog 코드 컨벤션](https://weak-sugar-603.notion.site/Code-a2f1656b941a42d0ac37c11f003a63a0?pvs=4)을 정하고 적용했습니다.
