### ISSUE TITLE
Feature: CI/CD 파이프라인을 구축한다.

### ISSUE THREAD

**Issue by Byeonjin** [boostcampwm2023/web13_Boarlog#5]
## Feature Description

애플리케이션 개발 단계 자동화를 위한 CI/CD 파이프라인 구축

## To-Do

- [X] Backend CI/CD 파이프라인 구축

**Comment by platinouss** [comment]
Docker를 사용하여 큰 무리없이 CI/CD 파이프라인을 구축했습니다.
구축하면서 도커 레이어 캐싱을 활용하면 빌드 시간을 단축시킬 수 있다는 점도 알게 되어, 한번 정리해 보았습니다.
[레이어 캐싱을 활용한 빌드시간 단축](https://weak-sugar-603.notion.site/2901b8dc444a4ce489f0e858884fb1bb?pvs=4)
