### ISSUE TITLE
Feature: 사용자의 프로필과 정보(닉네임, 이메일)을 확인할 수 있다.(서버요청 포함)

### ISSUE THREAD

**Issue by Byeonjin** [boostcampwm2023/web13_Boarlog#61]
## Feature Description

여기에 작성하세요

## To-Do

- [ ] Todo1
- [ ] Todo2
- [ ] Todo3

### 추가 사항

여기에 작성하세요

**Comment by LellowMellow** [comment]
다른 issue에서 해결한 기능이므로 close 합니다.
