### ISSUE TITLE
Feature: 로그아웃 버튼을 클릭하면 로그아웃 후 로그인 화면으로 이동한다. (서버 요청)

### ISSUE THREAD

**Issue by Byeonjin** [boostcampwm2023/web13_Boarlog#63]
## Feature Description

여기에 작성하세요

## To-Do

- [ ] Todo1
- [ ] Todo2
- [ ] Todo3

### 추가 사항

여기에 작성하세요

**Comment by LellowMellow** [comment]
로그아웃 기능을 제외하고 구현하였습니다. 구글 소셜 로그인을 제외하는 과정에서 해당 방식으로 구현 방향을 변경하였습니다.

**Comment by LellowMellow** [comment]
로그아웃 기능을 제외하고 구현하였습니다. 구글 소셜 로그인을 제외하는 과정에서 해당 방식으로 구현 방향을 변경하였습니다.
