### ISSUE TITLE
Feature: 서버로부터 받은 프로필 이미지와 닉네임을 표시한다.

### ISSUE THREAD

**Issue by Byeonjin** [boostcampwm2023/web13_Boarlog#9]
## Feature Description

여기에 작성하세요

## To-Do

- [ ] Todo1
- [ ] Todo2
- [ ] Todo3

### 추가 사항

여기에 작성하세요

**Comment by LellowMellow** [comment]
프로필 이미지를 활용하지 않고 단순히 닉네임과 이메일을 띄우는 방식으로 변경하였습니다. 다른 issue에서 해당 테스크를 처리하여 close 합니다.
